site_name: "Documentation | Dank"
site_author: dank.ooo
site_description: Dank is an Open Internet Service on DFINITY's Internet Computer that provides cycle-based financial services to developers & users.
site_url: https://docs.dank.ooo/
copyright: 'Â© 2021 Built by Dank'
repo_name: psychedelic/dank-docs
repo_url: https://github.com/psychedelic/dank-docs
theme:
  name: material
  custom_dir: overrides
  favicon: './imgs/fav-dank.ico'
  logo: './imgs/dank-w.png'
  font:
    text: 'Open Sans'
extra_css:
  - 'stylesheets/extra.css'
markdown_extensions:
  - codehilite
  - admonition
  - attr_list
  - meta
  - toc:
      permalink: true
nav:
  - Welcome to Dank ğŸ‘‹: index.md
  - Protocol Overview ğŸ—ºï¸:
    - How Dank Works: protocol-overview/how-dank-works.md
    - Participant Use Cases: protocol-overview/dank-use-cases.md
    - Common Terms : protocol-overview/common-terms.md       
  - Getting Started ğŸ:
      - Main Interface Overview: getting-started/overview.md
      - Setting Up Environment: getting-started/overview.md
      - Create/Interact with Accounts: getting-started/overview.md      
      - Send & operate with cycles: getting-started/overview.md
      - Create & manage canisters: getting-started/overview.md  
      - Authenticate users to IC Apps: getting-started/overview.md
      - Query data from Dank: getting-started/overview.md            
  - Interfaces ğŸ§°:
    - Main Dank Interface: canister-manager-proxy/overview.md
    - History Archive: canister-manager-proxy/overview.md
    - Ledger Node: canister-manager-proxy/overview.md    
  - Resources ğŸ’¡:
    - Resource Library: resources/library.md
    - Our App Ecosystem: resources/apps-with-dank.md
    - Dank's Blog: "https://medium.com/dank-ois"
    - Terms / Disclaimer: resources/disclaimer
    - Privacy Policy: resources/privacy
    - Trademark: resources/trademark
 
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/psychedelic/dank-canister
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/dank_ois
    - icon: fontawesome/brands/discord
      link: https://discord.gg/yVEcEzmrgm